
INSERT INTO itdp.country(name, alpha2, alpha3) VALUES
('Afghanistan',                                          'AF', 'AFG'),
('Åland Islands',                                        'AX', 'ALA'),
('Albania',                                              'AL', 'ALB'),
('Algeria',                                              'DZ', 'DZA'),
('American Samoa',                                       'AS', 'ASM'),
('Andorra',                                              'AD', 'AND'),
('Angola',                                               'AO', 'AGO'),
('Anguilla',                                             'AI', 'AIA'),
('Antarctica',                                           'AQ', 'ATA'),
('Antigua and Barbuda',                                  'AG', 'ATG'),
('Argentina',                                            'AR', 'ARG'),
('Armenia',                                              'AM', 'ARM'),
('Aruba',                                                'AW', 'ABW'),
('Australia',                                            'AU', 'AUS'),
('Austria',                                              'AT', 'AUT'),
('Azerbaijan',                                           'AZ', 'AZE'),
('Bahamas',                                              'BS', 'BHS'),
('Bahrain',                                              'BH', 'BHR'),
('Bangladesh',                                           'BD', 'BGD'),
('Barbados',                                             'BB', 'BRB'),
('Belarus',                                              'BY', 'BLR'),
('Belgium',                                              'BE', 'BEL'),
('Belize',                                               'BZ', 'BLZ'),
('Benin',                                                'BJ', 'BEN'),
('Bermuda',                                              'BM', 'BMU'),
('Bhutan',                                               'BT', 'BTN'),
('Bolivia (Plurinational State of)',                     'BO', 'BOL'),
('Bonaire, Sint Eustatius and Saba',                     'BQ', 'BES'),
('Bosnia and Herzegovina',                               'BA', 'BIH'),
('Botswana',                                             'BW', 'BWA'),
('Bouvet Island',                                        'BV', 'BVT'),
('Brazil',                                               'BR', 'BRA'),
('British Indian Ocean Territory',                       'IO', 'IOT'),
('Brunei Darussalam',                                    'BN', 'BRN'),
('Bulgaria',                                             'BG', 'BGR'),
('Burkina Faso',                                         'BF', 'BFA'),
('Burundi',                                              'BI', 'BDI'),
('Cambodia',                                             'KH', 'KHM'),
('Cameroon',                                             'CM', 'CMR'),
('Canada',                                               'CA', 'CAN'),
('Cabo Verde',                                           'CV', 'CPV'),
('Cayman Islands',                                       'KY', 'CYM'),
('Central African Republic',                             'CF', 'CAF'),
('Chad',                                                 'TD', 'TCD'),
('Chile',                                                'CL', 'CHL'),
('China',                                                'CN', 'CHN'),
('Christmas Island',                                     'CX', 'CXR'),
('Cocos (Keeling) Islands',                              'CC', 'CCK'),
('Colombia',                                             'CO', 'COL'),
('Comoros',                                              'KM', 'COM'),
('Congo',                                                'CG', 'COG'),
('Congo (Democratic Republic of the)',                   'CD', 'COD'),
('Cook Islands',                                         'CK', 'COK'),
('Costa Rica',                                           'CR', 'CRI'),
('Côte d''Ivoire',                                       'CI', 'CIV'),
('Croatia',                                              'HR', 'HRV'),
('Cuba',                                                 'CU', 'CUB'),
('Curaçao',                                              'CW', 'CUW'),
('Cyprus',                                               'CY', 'CYP'),
('Czech Republic',                                       'CZ', 'CZE'),
('Denmark',                                              'DK', 'DNK'),
('Djibouti',                                             'DJ', 'DJI'),
('Dominica',                                             'DM', 'DMA'),
('Dominican Republic',                                   'DO', 'DOM'),
('Ecuador',                                              'EC', 'ECU'),
('Egypt',                                                'EG', 'EGY'),
('El Salvador',                                          'SV', 'SLV'),
('Equatorial Guinea',                                    'GQ', 'GNQ'),
('Eritrea',                                              'ER', 'ERI'),
('Estonia',                                              'EE', 'EST'),
('Ethiopia',                                             'ET', 'ETH'),
('Falkland Islands (Malvinas)',                          'FK', 'FLK'),
('Faroe Islands',                                        'FO', 'FRO'),
('Fiji',                                                 'FJ', 'FJI'),
('Finland',                                              'FI', 'FIN'),
('France',                                               'FR', 'FRA'),
('French Guiana',                                        'GF', 'GUF'),
('French Polynesia',                                     'PF', 'PYF'),
('French Southern Territories',                          'TF', 'ATF'),
('Gabon',                                                'GA', 'GAB'),
('Gambia',                                               'GM', 'GMB'),
('Georgia',                                              'GE', 'GEO'),
('Germany',                                              'DE', 'DEU'),
('Ghana',                                                'GH', 'GHA'),
('Gibraltar',                                            'GI', 'GIB'),
('Greece',                                               'GR', 'GRC'),
('Greenland',                                            'GL', 'GRL'),
('Grenada',                                              'GD', 'GRD'),
('Guadeloupe',                                           'GP', 'GLP'),
('Guam',                                                 'GU', 'GUM'),
('Guatemala',                                            'GT', 'GTM'),
('Guernsey',                                             'GG', 'GGY'),
('Guinea',                                               'GN', 'GIN'),
('Guinea-Bissau',                                        'GW', 'GNB'),
('Guyana',                                               'GY', 'GUY'),
('Haiti',                                                'HT', 'HTI'),
('Heard Island and McDonald Islands',                    'HM', 'HMD'),
('Holy See',                                             'VA', 'VAT'),
('Honduras',                                             'HN', 'HND'),
('Hong Kong',                                            'HK', 'HKG'),
('Hungary',                                              'HU', 'HUN'),
('Iceland',                                              'IS', 'ISL'),
('India',                                                'IN', 'IND'),
('Indonesia',                                            'ID', 'IDN'),
('Iran (Islamic Republic of)',                           'IR', 'IRN'),
('Iraq',                                                 'IQ', 'IRQ'),
('Ireland',                                              'IE', 'IRL'),
('Isle of Man',                                          'IM', 'IMN'),
('Israel',                                               'IL', 'ISR'),
('Italy',                                                'IT', 'ITA'),
('Jamaica',                                              'JM', 'JAM'),
('Japan',                                                'JP', 'JPN'),
('Jersey',                                               'JE', 'JEY'),
('Jordan',                                               'JO', 'JOR'),
('Kazakhstan',                                           'KZ', 'KAZ'),
('Kenya',                                                'KE', 'KEN'),
('Kiribati',                                             'KI', 'KIR'),
('Korea (Democratic People''s Republic of)',             'KP', 'PRK'),
('Korea (Republic of)',                                  'KR', 'KOR'),
('Kuwait',                                               'KW', 'KWT'),
('Kyrgyzstan',                                           'KG', 'KGZ'),
('Lao People''s Democratic Republic',                    'LA', 'LAO'),
('Latvia',                                               'LV', 'LVA'),
('Lebanon',                                              'LB', 'LBN'),
('Lesotho',                                              'LS', 'LSO'),
('Liberia',                                              'LR', 'LBR'),
('Libya',                                                'LY', 'LBY'),
('Liechtenstein',                                        'LI', 'LIE'),
('Lithuania',                                            'LT', 'LTU'),
('Luxembourg',                                           'LU', 'LUX'),
('Macao',                                                'MO', 'MAC'),
('Macedonia (the former Yugoslav Republic of)',          'MK', 'MKD'),
('Madagascar',                                           'MG', 'MDG'),
('Malawi',                                               'MW', 'MWI'),
('Malaysia',                                             'MY', 'MYS'),
('Maldives',                                             'MV', 'MDV'),
('Mali',                                                 'ML', 'MLI'),
('Malta',                                                'MT', 'MLT'),
('Marshall Islands',                                     'MH', 'MHL'),
('Martinique',                                           'MQ', 'MTQ'),
('Mauritania',                                           'MR', 'MRT'),
('Mauritius',                                            'MU', 'MUS'),
('Mayotte',                                              'YT', 'MYT'),
('Mexico',                                               'MX', 'MEX'),
('Micronesia (Federated States of)',                     'FM', 'FSM'),
('Moldova (Republic of)',                                'MD', 'MDA'),
('Monaco',                                               'MC', 'MCO'),
('Mongolia',                                             'MN', 'MNG'),
('Montenegro',                                           'ME', 'MNE'),
('Montserrat',                                           'MS', 'MSR'),
('Morocco',                                              'MA', 'MAR'),
('Mozambique',                                           'MZ', 'MOZ'),
('Myanmar',                                              'MM', 'MMR'),
('Namibia',                                              'NA', 'NAM'),
('Nauru',                                                'NR', 'NRU'),
('Nepal',                                                'NP', 'NPL'),
('Netherlands',                                          'NL', 'NLD'),
('New Caledonia',                                        'NC', 'NCL'),
('New Zealand',                                          'NZ', 'NZL'),
('Nicaragua',                                            'NI', 'NIC'),
('Niger',                                                'NE', 'NER'),
('Nigeria',                                              'NG', 'NGA'),
('Niue',                                                 'NU', 'NIU'),
('Norfolk Island',                                       'NF', 'NFK'),
('Northern Mariana Islands',                             'MP', 'MNP'),
('Norway',                                               'NO', 'NOR'),
('Oman',                                                 'OM', 'OMN'),
('Pakistan',                                             'PK', 'PAK'),
('Palau',                                                'PW', 'PLW'),
('Palestine, State of',                                  'PS', 'PSE'),
('Panama',                                               'PA', 'PAN'),
('Papua New Guinea',                                     'PG', 'PNG'),
('Paraguay',                                             'PY', 'PRY'),
('Peru',                                                 'PE', 'PER'),
('Philippines',                                          'PH', 'PHL'),
('Pitcairn',                                             'PN', 'PCN'),
('Poland',                                               'PL', 'POL'),
('Portugal',                                             'PT', 'PRT'),
('Puerto Rico',                                          'PR', 'PRI'),
('Qatar',                                                'QA', 'QAT'),
('Réunion',                                              'RE', 'REU'),
('Romania',                                              'RO', 'ROU'),
('Russian Federation',                                   'RU', 'RUS'),
('Rwanda',                                               'RW', 'RWA'),
('Saint Barthélemy',                                     'BL', 'BLM'),
('Saint Helena, Ascension and Tristan da Cunha',         'SH', 'SHN'),
('Saint Kitts and Nevis',                                'KN', 'KNA'),
('Saint Lucia',                                          'LC', 'LCA'),
('Saint Martin (French part)',                           'MF', 'MAF'),
('Saint Pierre and Miquelon',                            'PM', 'SPM'),
('Saint Vincent and the Grenadines',                     'VC', 'VCT'),
('Samoa',                                                'WS', 'WSM'),
('San Marino',                                           'SM', 'SMR'),
('Sao Tome and Principe',                                'ST', 'STP'),
('Saudi Arabia',                                         'SA', 'SAU'),
('Senegal',                                              'SN', 'SEN'),
('Serbia',                                               'RS', 'SRB'),
('Seychelles',                                           'SC', 'SYC'),
('Sierra Leone',                                         'SL', 'SLE'),
('Singapore',                                            'SG', 'SGP'),
('Sint Maarten (Dutch part)',                            'SX', 'SXM'),
('Slovakia',                                             'SK', 'SVK'),
('Slovenia',                                             'SI', 'SVN'),
('Solomon Islands',                                      'SB', 'SLB'),
('Somalia',                                              'SO', 'SOM'),
('South Africa',                                         'ZA', 'ZAF'),
('South Georgia and the South Sandwich Islands',         'GS', 'SGS'),
('South Sudan',                                          'SS', 'SSD'),
('Spain',                                                'ES', 'ESP'),
('Sri Lanka',                                            'LK', 'LKA'),
('Sudan',                                                'SD', 'SDN'),
('Suriname',                                             'SR', 'SUR'),
('Svalbard and Jan Mayen',                               'SJ', 'SJM'),
('Swaziland',                                            'SZ', 'SWZ'),
('Sweden',                                               'SE', 'SWE'),
('Switzerland',                                          'CH', 'CHE'),
('Syrian Arab Republic',                                 'SY', 'SYR'),
('Taiwan, Province of China',                            'TW', 'TWN'),
('Tajikistan',                                           'TJ', 'TJK'),
('Tanzania, United Republic of',                         'TZ', 'TZA'),
('Thailand',                                             'TH', 'THA'),
('Timor-Leste',                                          'TL', 'TLS'),
('Togo',                                                 'TG', 'TGO'),
('Tokelau',                                              'TK', 'TKL'),
('Tonga',                                                'TO', 'TON'),
('Trinidad and Tobago',                                  'TT', 'TTO'),
('Tunisia',                                              'TN', 'TUN'),
('Turkey',                                               'TR', 'TUR'),
('Turkmenistan',                                         'TM', 'TKM'),
('Turks and Caicos Islands',                             'TC', 'TCA'),
('Tuvalu',                                               'TV', 'TUV'),
('Uganda',                                               'UG', 'UGA'),
('Ukraine',                                              'UA', 'UKR'),
('United Arab Emirates',                                 'AE', 'ARE'),
('United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR'),
('United States of America',                             'US', 'USA'),
('United States Minor Outlying Islands',                 'UM', 'UMI'),
('Uruguay',                                              'UY', 'URY'),
('Uzbekistan',                                           'UZ', 'UZB'),
('Vanuatu',                                              'VU', 'VUT'),
('Venezuela (Bolivarian Republic of)',                   'VE', 'VEN'),
('Viet Nam',                                             'VN', 'VNM'),
('Virgin Islands (British)',                             'VG', 'VGB'),
('Virgin Islands (U.S.)',                                'VI', 'VIR'),
('Wallis and Futuna',                                    'WF', 'WLF'),
('Western Sahara',                                       'EH', 'ESH'),
('Yemen',                                                'YE', 'YEM'),
('Zambia',                                               'ZM', 'ZMB'),
('Zimbabwe',                                             'ZW', 'ZWE')
ON CONFLICT DO NOTHING ;





-- TODO: Populate table 'language'.
INSERT INTO itdp.language(name, alpha2, alpha3t, alpha3b) VALUES
	('English', 'en', 'eng', 'eng'),
	('German',  'de', 'deu', 'ger')
ON CONFLICT DO NOTHING ;


-- Contact Types
INSERT INTO itdp.contact_type (id,name) 
    VALUES 
        ('061e7edf-1b00-454c-b10b-562e226c8500','individual'),
        ('99fdcfe1-b7fc-4e57-8c35-9887b2149056','organization') ON CONFLICT DO NOTHING ;


INSERT INTO itdp.domain_contact_type (id,name) 
    VALUES 
        ('5a869dcd-0435-430a-9dfa-2ab286da3ab8','registrant'),
        ('7b9d05e4-88a1-42aa-a050-5d30f4b833e2','admin'),
        ('a95636da-8399-4867-9797-f8452269003b','tech'),
        ('14036972-309f-443e-8c16-5115356bb68d','billing')
 ON CONFLICT DO NOTHING ;    

 INSERT INTO itdp.lock_type (id,"name", descr) VALUES  
   ('3d0af86b-4d98-4ad1-9823-1e91108fe5ae','update', 'Requests to update the object MUST be rejected') ,
   ('ee070b2a-e75b-42b8-9469-5146db9b9221','delete','Requests to delete the object MUST be rejected'),
   ('8261baeb-89fc-4020-9e05-b17158f11d9c','transfer', 'Requests to transfer the object MUST be rejected'),
   ('3d97d496-4f1d-11e8-9bfd-02420a000396','hold','Signify that the object is on hold')
ON CONFLICT DO NOTHING ;

INSERT INTO itdp.domain_status (id,name, descr) 
    VALUES 
        ('ddfa2bed-e332-40b9-9244-2440ffa2d555','Active', 'Domain is active'),
        ('24ac43cb-ff01-459a-8ed7-d1846b0404aa','Deleted', 'Domain is deleted in registry'), 
        ('ad4432b5-b99c-4385-ac33-477e6446216f','Expired', 'Domain has passed its expiration date'),
        ('b6131b33-1f4e-4169-93d7-6795009c3e7e','Extended RGP','Domain has entered its Redemption Grace Period (RGP), but will become part of our portfolio, or in some cases, could not be deleted normally'),
		('c0928677-ca0b-49fd-9df7-43446f9889cc','RGP','Domain name has passed  expiration grace period and is scheduled for deletion')
	
ON CONFLICT DO NOTHING ;