// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	datamanager "github.com/tucowsinc/tdp-messages-go/message/datamanager"
)

// Service is an autogenerated mock type for the iService type
type Service struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, notification, msgHeaders
func (_m *Service) SendEmail(ctx context.Context, notification *datamanager.Notification, msgHeaders map[string]interface{}) error {
	ret := _m.Called(ctx, notification, msgHeaders)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *datamanager.Notification, map[string]interface{}) error); ok {
		r0 = rf(ctx, notification, msgHeaders)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
