package v1

import (
	"errors"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	_ "github.com/lpar/problem"
	"github.com/tucowsinc/tdp-messagebus-go/pkg/messagebus"
	tcwire "github.com/tucowsinc/tdp-messages-go/message"
	"github.com/tucowsinc/tdp-notifications/api-service/internal/app/models"
	"github.com/tucowsinc/tdp-notifications/api-service/internal/pkg/error_handling"
	"github.com/tucowsinc/tdp-notifications/api-service/internal/pkg/gcontext"
	"github.com/tucowsinc/tdp-notifications/api-service/internal/pkg/messaging"
)

// GetSubscriptionHandler godoc
// @Summary		Get subscription by ID
// @Schemes
// @Description	Gets subscription by ID
// @Tags		subscriptions
// @Produces	json
// @Accepts		json
// @Param		id path string true "Subscription ID"
// @Param		idempotency-key header string false "An idempotency key is a unique value generated by the client which the server uses to recognize subsequent retries of the same request."
// @Param		x-version header string true "The API version"
// @Param		x-tenant-customer-id header string true "Tenant customer ID"
// @Success		200 {object} models.SubscriptionGetResponse
// @Failure		400 {object} problem.ProblemDetails
// @Failure		401 {object} problem.ProblemDetails
// @Failure		403 {object} problem.ProblemDetails
// @Failure		404 {object} problem.ProblemDetails
// @Failure		408 {object} problem.ProblemDetails
// @Failure		429 {object} problem.ProblemDetails
// @Failure		500 {object} problem.ProblemDetails
// @Header		201,202,400,401,403,408,429	{string} x-transaction-id "Unique request identifier"
// @Header		201,202,400,401,403,408,429	{int} x-request-duration "Time in seconds it took to receive the response"
// @Header		201,202,400,401,403,408,429	{int} x-rate-limit "Total number of available requests before being throttled"
// @Header		201,202,400,401,403,408,429	{int} x-rate-limit-remaining "Remaining number of available requests"
// @Header		201,202,400,401,403,408,429	{string} x-version "The api version"
// @Header		429 {int} retry-after "Number of seconds to wait before making additional requests"
// @Router		/api/subscriptions/{id} [get]
func (h *Handler) GetSubscriptionHandler(c *gin.Context) {
	params := models.SubscriptionGetParameter{}

	// Validate URI parameters and Bind those to parameters structure
	if err := c.ShouldBindUri(&params); err != nil {
		var ve validator.ValidationErrors
		if errors.As(err, &ve) {
			error_handling.ValidationErrorResponse("", ve, c)
			return
		}
		error_handling.BadRequestErrorResponse("", c)
		return
	}

	// Extract headers
	headers := messaging.GetHeaders(c)

	// Call the service method to fetch subscription by ID
	res, err := h.s.GetSubscription(c.Request.Context(), &params, headers, gcontext.GetBaseHeader(c))

	// Handle message bus timeout
	if errors.Is(err, messagebus.ErrCallTimeout) {
		error_handling.RequestTimeoutResponse("message bus call timeout", c)
		return
	}

	// Handle message bus errors
	if busErr := new(messaging.BusErr); errors.As(err, &busErr) {
		// Check if the error indicates that the subscription was not found (404)
		if busErr.ErrorResponse.AppCode == tcwire.ErrorResponse_NOT_FOUND {
			error_handling.NotFoundErrorResponse("Subscription not found", c)
			return
		}

		error_handling.HandleMessageBusErrorResponse(c, h.logger, busErr.ErrorResponse)
		return
	}

	if err != nil {
		error_handling.InternalServerErrorResponse("failed to get subscription", h.logger, c)
		return
	}

	c.JSON(http.StatusOK, res)
}
