# These values are used for local run
# For DEV they will be overwritten during deployment

log:
  outputsink: stderr

rmq:
  hostname: rabbitmq-local
  port: 5671
  username: domains
  password: tucows
  exchange: test
  queuetype: classic
  tlsenabled: true
  tlsskipverify: true
  webhookQueue:
    queuename: webhook_notification
  emailQueue:
    queuename: email_notification
  verifyservername:

subscriptiondb:
  hostname: subdb
  port: 5432
  username: tucows
  password: tucows1234
  dbname: subtdpdb
