
// this is a very basic test for the model
// please do not change this file since its contents
// are automatically generated by schemadump
package db

import (
  "fmt"
  "testing"
)

func ExampleConnect() {
  _, err := Connect("user=tucows dbname=tdpdb host=localhost port=5432 sslmode=disable")

  if err == nil {
    fmt.Println("successfully connected to the db")
  } else {
    fmt.Println("failed to connect to the db: ", err)
  }
  // Output: successfully connected to the db
}

func TestConnect( t *testing.T ){
  _, err := Connect("user=db dbname=tucows host=tdpdb port=0 sslmode=disable")

  if err == nil {
    fmt.Println("successfully connected to the db")
  }

}

