version: '3.7'

services:
  sample-db:
    build:
      context: .
      dockerfile: Dockerfile
    # image: postgres:14.5
    environment:
      - POSTGRES_USER=tucows
      - POSTGRES_PASSWORD=tucows1234
      # add the following lines pointing to a local directory if you need
      # the database to be persistent
      # volumes:
      #   - ./data/db:/var/lib/postgresql/data
    volumes:
      - ./etc/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/t:/tests/db/t
      - ./db:/db
    working_dir: /db
    healthcheck:
      test: if [ ! -f ../ready ]; then touch ../ready && make all test-data; fi
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 1m
    ports:
      - "5432:5432"
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
