// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubscriptionWebhookChannel = "subscription_webhook_channel"

// SubscriptionWebhookChannel mapped from table <subscription_webhook_channel>
type SubscriptionWebhookChannel struct {
	CreatedDate *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy   *string    `gorm:"column:created_by;type:text;->" json:"created_by"`
	UpdatedBy   *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	DeletedDate *time.Time `gorm:"column:deleted_date;type:timestamp with time zone" json:"deleted_date"`
	DeletedBy   *string    `gorm:"column:deleted_by;type:text" json:"deleted_by"`

	ID             string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TypeID         string `gorm:"column:type_id;type:uuid;not null;<-:update" json:"type_id"`
	SubscriptionID string `gorm:"column:subscription_id;type:uuid;not null" json:"subscription_id"`
	WebhookURL     string `gorm:"column:webhook_url;type:text;not null" json:"webhook_url"`
	SigningSecret  string `gorm:"column:signing_secret;type:text;not null" json:"signing_secret"`
}

// TableName SubscriptionWebhookChannel's table name
func (*SubscriptionWebhookChannel) TableName() string {
	return TableNameSubscriptionWebhookChannel
}
