// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVTenantCustomer = "v_tenant_customer"

// VTenantCustomer mapped from table <v_tenant_customer>
type VTenantCustomer struct {
	TenantID                  *string    `gorm:"column:tenant_id;type:uuid" json:"tenant_id"`
	CustomerID                *string    `gorm:"column:customer_id;type:uuid" json:"customer_id"`
	TenantName                *string    `gorm:"column:tenant_name;type:text" json:"tenant_name"`
	TenantDescr               *string    `gorm:"column:tenant_descr;type:text" json:"tenant_descr"`
	CustomerNumber            *string    `gorm:"column:customer_number;type:text" json:"customer_number"`
	ID                        *string    `gorm:"column:id;type:uuid" json:"id"`
	Name                      *string    `gorm:"column:name;type:text" json:"name"`
	Descr                     *string    `gorm:"column:descr;type:text" json:"descr"`
	CustomerCreatedDate       *time.Time `gorm:"column:customer_created_date;type:timestamp with time zone" json:"customer_created_date"`
	CustomerUpdatedDate       *time.Time `gorm:"column:customer_updated_date;type:timestamp with time zone" json:"customer_updated_date"`
	TenantCustomerCreatedDate *time.Time `gorm:"column:tenant_customer_created_date;type:timestamp with time zone" json:"tenant_customer_created_date"`
	TenantCustomerUpdatedDate *time.Time `gorm:"column:tenant_customer_updated_date;type:timestamp with time zone" json:"tenant_customer_updated_date"`
}

// TableName VTenantCustomer's table name
func (*VTenantCustomer) TableName() string {
	return TableNameVTenantCustomer
}
