// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVNotification = "v_notification"

// VNotification mapped from table <v_notification>
type VNotification struct {
	ID               *string    `gorm:"column:id;type:uuid" json:"id"`
	NotificationID   *string    `gorm:"column:notification_id;type:uuid" json:"notification_id"`
	Type             *string    `gorm:"column:type;type:text" json:"type"`
	Payload          *string    `gorm:"column:payload;type:jsonb" json:"payload"`
	CreatedDate      *time.Time `gorm:"column:created_date;type:timestamp with time zone" json:"created_date"`
	TenantID         *string    `gorm:"column:tenant_id;type:uuid" json:"tenant_id"`
	TenantCustomerID *string    `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	Status           *string    `gorm:"column:status;type:text" json:"status"`
	Retries          *int32     `gorm:"column:retries;type:integer" json:"retries"`
	ChannelType      *string    `gorm:"column:channel_type;type:text" json:"channel_type"`
	SubscriptionID   *string    `gorm:"column:subscription_id;type:uuid" json:"subscription_id"`
	WebhookURL       *string    `gorm:"column:webhook_url;type:text" json:"webhook_url"`
	SigningSecret    *string    `gorm:"column:signing_secret;type:text" json:"signing_secret"`
	EmailSubject     *string    `gorm:"column:email_subject;type:text" json:"email_subject"`
	EmailTemplate    *string    `gorm:"column:email_template;type:text" json:"email_template"`
	StatusID         *string    `gorm:"column:status_id;type:uuid" json:"status_id"`
}

// TableName VNotification's table name
func (*VNotification) TableName() string {
	return TableNameVNotification
}

func (p *VNotification) GetID() string {
	if p.ID == nil {
		return ""
	}
	return *p.ID
}

func (p *VNotification) GetNotificationID() string {
	if p.NotificationID == nil {
		return ""
	}
	return *p.NotificationID
}
