// Code generated by mockery v2.46.1. DO NOT EDIT.

package handlersmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	datamanager "github.com/tucowsinc/tdp-messages-go/message/datamanager"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// GetNotificationByID provides a mock function with given fields: ctx, id
func (_m *IService) GetNotificationByID(ctx context.Context, id string) (*datamanager.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationByID")
	}

	var r0 *datamanager.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*datamanager.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *datamanager.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datamanager.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationStatus provides a mock function with given fields: _a0, _a1
func (_m *IService) UpdateNotificationStatus(_a0 context.Context, _a1 *datamanager.Notification) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *datamanager.Notification) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIService creates a new instance of IService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IService {
	mock := &IService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
