// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameContact = "contact"

// Contact mapped from table <contact>
type Contact struct {
	CreatedDate      *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate      *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy        *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy        *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	DeletedDate      *time.Time `gorm:"column:deleted_date;type:timestamp with time zone" json:"deleted_date"`
	DeletedBy        *string    `gorm:"column:deleted_by;type:text" json:"deleted_by"`
	ID               string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TypeID           string     `gorm:"column:type_id;type:uuid;not null" json:"type_id"`
	Title            *string    `gorm:"column:title;type:text" json:"title"`
	OrgReg           *string    `gorm:"column:org_reg;type:text" json:"org_reg"`
	SalesTax         *string    `gorm:"column:sales_tax;type:text" json:"sales_tax"`
	OrgDuns          *string    `gorm:"column:org_duns;type:text" json:"org_duns"`
	TenantCustomerID *string    `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	Email            *string    `gorm:"column:email;type:mbox" json:"email"`
	Phone            *string    `gorm:"column:phone;type:text" json:"phone"`
	PhoneExt         *string    `gorm:"column:phone_ext;type:text" json:"phone_ext"`
	Fax              *string    `gorm:"column:fax;type:text" json:"fax"`
	FaxExt           *string    `gorm:"column:fax_ext;type:text" json:"fax_ext"`
	Country          string     `gorm:"column:country;type:text;not null" json:"country"`
	Language         *string    `gorm:"column:language;type:text" json:"language"`
	Tags             *string    `gorm:"column:tags;type:text[]" json:"tags"`
	Documentation    *string    `gorm:"column:documentation;type:text[]" json:"documentation"`
	ShortID          string     `gorm:"column:short_id;type:text;not null;default:gen_short_id()" json:"short_id"`
	Metadata         *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	MigrationInfo    *string    `gorm:"column:migration_info;type:jsonb;default:{};comment:Contains migration information as example - {"data_source": "Enom", "invalid_fields": ["country"], "lost_handle": true, "placeholder": true}" json:"migration_info"` // Contains migration information as example - {"data_source": "Enom", "invalid_fields": ["country"], "lost_handle": true, "placeholder": true}
}

// TableName Contact's table name
func (*Contact) TableName() string {
	return TableNameContact
}
