// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDomainContactType = "domain_contact_type"

// DomainContactType mapped from table <domain_contact_type>
type DomainContactType struct {
	ID    string  `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name  string  `gorm:"column:name;type:text;not null" json:"name"`
	Descr *string `gorm:"column:descr;type:text" json:"descr"`
}

// TableName DomainContactType's table name
func (*DomainContactType) TableName() string {
	return TableNameDomainContactType
}
