// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomainRgpStatus = "domain_rgp_status"

// DomainRgpStatus mapped from table <domain_rgp_status>
type DomainRgpStatus struct {
	ID          string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	DomainID    string     `gorm:"column:domain_id;type:uuid;not null" json:"domain_id"`
	StatusID    string     `gorm:"column:status_id;type:uuid;not null" json:"status_id"`
	CreatedDate *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	ExpiryDate  *time.Time `gorm:"column:expiry_date;type:timestamp with time zone;not null" json:"expiry_date"`
}

// TableName DomainRgpStatus's table name
func (*DomainRgpStatus) TableName() string {
	return TableNameDomainRgpStatus
}
