// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEvent = "event"

// Event mapped from table <event>
type Event struct {
	ID          string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	ReferenceID *string    `gorm:"column:reference_id;type:uuid" json:"reference_id"`
	TenantID    string     `gorm:"column:tenant_id;type:uuid;not null" json:"tenant_id"`
	TypeID      string     `gorm:"column:type_id;type:uuid;not null" json:"type_id"`
	Payload     string     `gorm:"column:payload;type:jsonb;not null" json:"payload"`
	Header      *string    `gorm:"column:header;type:jsonb" json:"header"`
	IsProcessed bool       `gorm:"column:is_processed;type:boolean;primaryKey" json:"is_processed"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
