// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHost = "host"

// Host mapped from table <host>
type Host struct {
	CreatedDate      *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate      *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy        *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy        *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID               string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TenantCustomerID string     `gorm:"column:tenant_customer_id;type:uuid;not null" json:"tenant_customer_id"`
	Name             string     `gorm:"column:name;type:text;not null" json:"name"`
	DomainID         *string    `gorm:"column:domain_id;type:uuid" json:"domain_id"`
	Metadata         *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`

	HostAddrs []HostAddr `gorm:"foreignKey:host_id"`
}

// TableName Host's table name
func (*Host) TableName() string {
	return TableNameHost
}
