// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHostingProduct = "hosting_product"

// HostingProduct mapped from table <hosting_product>
type HostingProduct struct {
	CreatedDate *time.Time `gorm:"column:created_date;default:now()" json:"created_date"`
	UpdatedDate *time.Time `gorm:"column:updated_date" json:"updated_date"`
	CreatedBy   *string    `gorm:"column:created_by;default:CURRENT_USER" json:"created_by"`
	UpdatedBy   *string    `gorm:"column:updated_by" json:"updated_by"`
	ID          string     `gorm:"column:id;primaryKey" json:"id"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	IsActive    bool       `gorm:"column:is_active;not null" json:"is_active"`
}

// TableName HostingProduct's table name
func (*HostingProduct) TableName() string {
	return TableNameHostingProduct
}
