// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHostingStatus = "hosting_status"

// HostingStatus mapped from table <hosting_status>
type HostingStatus struct {
	ID    string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name  string `gorm:"column:name;type:text;not null" json:"name"`
	Descr string `gorm:"column:descr;type:text;not null" json:"descr"`
}

// TableName HostingStatus's table name
func (*HostingStatus) TableName() string {
	return TableNameHostingStatus
}
