// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHostAddr = "host_addr"

// HostAddr mapped from table <host_addr>
type HostAddr struct {
	CreatedDate *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy   *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy   *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID          string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	HostID      string     `gorm:"column:host_id;type:uuid;not null" json:"host_id"`
	Address     *string    `gorm:"column:address;type:inet" json:"address"`
}

// TableName HostAddr's table name
func (*HostAddr) TableName() string {
	return TableNameHostAddr
}
