// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderItemTransferAwayDomain = "order_item_transfer_away_domain"

// OrderItemTransferAwayDomain mapped from table <order_item_transfer_away_domain>
type OrderItemTransferAwayDomain struct {
	CreatedDate        *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate        *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy          *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy          *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID                 *string    `gorm:"<-:update column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	OrderID            string     `gorm:"column:order_id;type:uuid;not null" json:"order_id"`
	StatusID           string     `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('order_item_status'::text, 'pending'::text)" json:"status_id"`
	ParentOrderItemID  *string    `gorm:"column:parent_order_item_id;type:uuid" json:"parent_order_item_id"`
	DomainID           *string    `gorm:"column:domain_id;type:uuid;not null" json:"domain_id"`
	Name               string     `gorm:"column:name;type:fqdn;not null" json:"name"`
	TransferStatusID   string     `gorm:"column:transfer_status_id;type:uuid;not null" json:"transfer_status_id"`
	RequestedBy        string     `gorm:"column:requested_by;type:text;not null" json:"requested_by"`
	RequestedDate      time.Time  `gorm:"column:requested_date;type:timestamp with time zone;not null" json:"requested_date"`
	ActionBy           string     `gorm:"column:action_by;type:text" json:"action_by"`
	ActionDate         time.Time  `gorm:"column:action_date;type:timestamp with time zone" json:"action_date"`
	ExpiryDate         time.Time  `gorm:"column:expiry_date;type:timestamp with time zone" json:"expiry_date"`
	AccreditationTldID *string    `gorm:"column:accreditation_tld_id;type:uuid;not null" json:"accreditation_tld_id"`
}

// TableName OrderItemTransferAwayDomain's table name
func (*OrderItemTransferAwayDomain) TableName() string {
	return TableNameOrderItemTransferAwayDomain
}
