// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderItemPlanStatus = "order_item_plan_status"

// OrderItemPlanStatus mapped from table <order_item_plan_status>
type OrderItemPlanStatus struct {
	CreatedDate *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy   *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy   *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID          string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string     `gorm:"column:name;type:text;not null" json:"name"`
	Descr       *string    `gorm:"column:descr;type:text" json:"descr"`
	IsSuccess   bool       `gorm:"column:is_success;type:boolean;not null" json:"is_success"`
	IsFinal     bool       `gorm:"column:is_final;type:boolean;not null" json:"is_final"`
}

// TableName OrderItemPlanStatus's table name
func (*OrderItemPlanStatus) TableName() string {
	return TableNameOrderItemPlanStatus
}
