// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderItemPlan = "order_item_plan"

// OrderItemPlan mapped from table <order_item_plan>
type OrderItemPlan struct {
	ID                 string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	OrderItemID        string     `gorm:"column:order_item_id;type:uuid;not null" json:"order_item_id"`
	ParentID           *string    `gorm:"column:parent_id;type:uuid" json:"parent_id"`
	StatusID           string     `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('order_item_plan_status'::text, 'new'::text)" json:"status_id"`
	ValidationStatusID string     `gorm:"column:validation_status_id;type:uuid;not null;default:tc_id_from_name('order_item_plan_validation_status'::text, 'pending'::text)" json:"validation_status_id"`
	OrderItemObjectID  string     `gorm:"column:order_item_object_id;type:uuid;not null" json:"order_item_object_id"`
	ReferenceID        *string    `gorm:"column:reference_id;type:uuid" json:"reference_id"`
	ResultMessage      *string    `gorm:"column:result_message;type:text" json:"result_message"`
	ResultData         *string    `gorm:"column:result_data;type:jsonb" json:"result_data"`
	ValidationData     *string    `gorm:"column:validation_data;type:jsonb" json:"validation_data"`
	ProvisionOrder     *int32     `gorm:"column:provision_order;type:integer" json:"provision_order"`
	CreatedDate        *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate        *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy          *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy          *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
}

// TableName CreateDomainPlan's table name
func (*OrderItemPlan) TableName() string {
	return TableNameOrderItemPlan
}
