// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePollMessageStatus = "poll_message_status"

// PollMessageStatus mapped from table <poll_message_status>
type PollMessageStatus struct {
	ID    string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name  string `gorm:"column:name;type:text;not null" json:"name"`
	Descr string `gorm:"column:descr;type:text;not null" json:"descr"`
}

// TableName PollMessageStatus's table name
func (*PollMessageStatus) TableName() string {
	return TableNamePollMessageStatus
}
