// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProvisionStatus = "provision_status"

// ProvisionStatus mapped from table <provision_status>
type ProvisionStatus struct {
	ID        string  `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name      string  `gorm:"column:name;type:text;not null;uniqueIndex:provision_status_name_key,priority:1" json:"name"`
	Descr     *string `gorm:"column:descr;type:text" json:"descr"`
	IsSuccess bool    `gorm:"column:is_success;type:boolean;not null" json:"is_success"`
	IsFinal   bool    `gorm:"column:is_final;type:boolean;not null" json:"is_final"`
}

// TableName ProvisionStatus's table name
func (*ProvisionStatus) TableName() string {
	return TableNameProvisionStatus
}
