// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvisionDomainRenew = "provision_domain_renew"

// ProvisionDomainRenew mapped from table <provision_domain_renew>
type ProvisionDomainRenew struct {
	CreatedDate       *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate       *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy         *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy         *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID                string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TenantCustomerID  string     `gorm:"column:tenant_customer_id;type:uuid;not null" json:"tenant_customer_id"`
	ProvisionedDate   *time.Time `gorm:"column:provisioned_date;type:timestamp with time zone" json:"provisioned_date"`
	StatusID          string     `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('provision_status'::text, 'pending'::text)" json:"status_id"`
	Roid              *string    `gorm:"column:roid;type:text" json:"roid"`
	JobID             *string    `gorm:"column:job_id;type:uuid" json:"job_id"`
	OrderItemPlanIds  *string    `gorm:"column:order_item_plan_ids;type:uuid[]" json:"order_item_plan_ids"`
	ResultMessage     *string    `gorm:"column:result_message;type:text" json:"result_message"`
	ResultData        *string    `gorm:"column:result_data;type:jsonb" json:"result_data"`
	DomainID          *string    `gorm:"column:domain_id;type:uuid" json:"domain_id"`
	AccreditationID   string     `gorm:"column:accreditation_id;type:uuid;not null" json:"accreditation_id"`
	Period            *int32     `gorm:"column:period;type:integer;not null;default:1" json:"period"`
	CurrentExpiryDate time.Time  `gorm:"column:current_expiry_date;type:timestamp with time zone;not null" json:"current_expiry_date"`
	IsAuto            bool       `gorm:"column:is_auto;type:boolean;not null" json:"is_auto"`
	RyExpiryDate      *time.Time `gorm:"column:ry_expiry_date;type:timestamp with time zone" json:"ry_expiry_date"`
	OrderMetadata     *string    `gorm:"column:order_metadata;type:jsonb;default:{}" json:"order_metadata"`
	RyCltrid          *string    `gorm:"column:ry_cltrid;type:text" json:"ry_cltrid"`
	DomainName        string     `gorm:"column:domain_name;type:fqdn;not null" json:"domain_name"`
	AttemptCount      *int32     `gorm:"column:attempt_count;type:integer;default:1" json:"attempt_count"`
	AllowedAttempts   *int32     `gorm:"column:allowed_attempts;type:integer;default:1" json:"allowed_attempts"`
}

// TableName ProvisionDomainRenew's table name
func (*ProvisionDomainRenew) TableName() string {
	return TableNameProvisionDomainRenew
}
