// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/lib/pq"
	"time"
)

const TableNameProvisionDomainTransferIn = "provision_domain_transfer_in"

// ProvisionDomainTransferIn mapped from table <provision_domain_transfer_in>
type ProvisionDomainTransferIn struct {
	CreatedDate                *time.Time      `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate                *time.Time      `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy                  *string         `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy                  *string         `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID                         string          `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TenantCustomerID           string          `gorm:"column:tenant_customer_id;type:uuid;not null" json:"tenant_customer_id"`
	ProvisionedDate            *time.Time      `gorm:"column:provisioned_date;type:timestamp with time zone" json:"provisioned_date"`
	StatusID                   string          `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('provision_status'::text, 'pending'::text)" json:"status_id"`
	Roid                       *string         `gorm:"column:roid;type:text" json:"roid"`
	JobID                      *string         `gorm:"column:job_id;type:uuid" json:"job_id"`
	OrderItemPlanIds           *string         `gorm:"column:order_item_plan_ids;type:uuid[]" json:"order_item_plan_ids"`
	OrderMetadata              *string         `gorm:"column:order_metadata;type:jsonb;default:{}" json:"order_metadata"`
	ResultMessage              *string         `gorm:"column:result_message;type:text" json:"result_message"`
	ResultData                 *string         `gorm:"column:result_data;type:jsonb" json:"result_data"`
	DomainName                 string          `gorm:"column:domain_name;type:fqdn;not null" json:"domain_name"`
	AccreditationID            string          `gorm:"column:accreditation_id;type:uuid;not null" json:"accreditation_id"`
	AccreditationTldID         string          `gorm:"column:accreditation_tld_id;type:uuid;not null" json:"accreditation_tld_id"`
	ProvisionTransferRequestID *string         `gorm:"column:provision_transfer_request_id;type:uuid" json:"provision_transfer_request_id"`
	Pw                         *string         `gorm:"column:pw;type:text" json:"pw"`
	RyCreatedDate              *time.Time      `gorm:"column:ry_created_date;type:timestamp with time zone" json:"ry_created_date"`
	RyExpiryDate               *time.Time      `gorm:"column:ry_expiry_date;type:timestamp with time zone" json:"ry_expiry_date"`
	RyUpdatedDate              *time.Time      `gorm:"column:ry_updated_date;type:timestamp with time zone" json:"ry_updated_date"`
	RyTransferedDate           *time.Time      `gorm:"column:ry_transfered_date;type:timestamp with time zone" json:"ry_transfered_date"`
	Hosts                      *pq.StringArray `gorm:"column:hosts;type:fqdn[]" json:"hosts"`
	Tags                       *string         `gorm:"column:tags;type:text[]" json:"tags"`
	Metadata                   *string         `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	SecdnsType                 *string         `gorm:"column:secdns_type;type:secdns_data_type" json:"secdns_type"`
	Uname                      *string         `gorm:"column:uname;type:text" json:"uname"`
	Language                   *string         `gorm:"column:language;type:text" json:"language"`
	AttemptCount               *int32          `gorm:"column:attempt_count;type:integer;default:1" json:"attempt_count"`
	AllowedAttempts            *int32          `gorm:"column:allowed_attempts;type:integer;default:1" json:"allowed_attempts"`
}

// TableName ProvisionDomainTransferIn's table name
func (*ProvisionDomainTransferIn) TableName() string {
	return TableNameProvisionDomainTransferIn
}
