// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvisionHostingDelete = "provision_hosting_delete"

// ProvisionHostingDelete mapped from table <provision_hosting_delete>
type ProvisionHostingDelete struct {
	CreatedDate      *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate      *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy        *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy        *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID               string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TenantCustomerID string     `gorm:"column:tenant_customer_id;type:uuid;not null" json:"tenant_customer_id"`
	ProvisionedDate  *time.Time `gorm:"column:provisioned_date;type:timestamp with time zone" json:"provisioned_date"`
	StatusID         string     `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('provision_status'::text, 'pending'::text)" json:"status_id"`
	Roid             *string    `gorm:"column:roid;type:text" json:"roid"`
	JobID            *string    `gorm:"column:job_id;type:uuid" json:"job_id"`
	OrderItemPlanIds *string    `gorm:"column:order_item_plan_ids;type:uuid[]" json:"order_item_plan_ids"`
	ResultMessage    *string    `gorm:"column:result_message;type:text" json:"result_message"`
	ResultData       *string    `gorm:"column:result_data;type:jsonb" json:"result_data"`
	HostingID        string     `gorm:"column:hosting_id;type:uuid;not null" json:"hosting_id"`
	ExternalOrderID  *string    `gorm:"column:external_order_id;type:text" json:"external_order_id"`
	HostingStatusID  *string    `gorm:"column:hosting_status_id;type:uuid" json:"hosting_status_id"`
	IsActive         *bool      `gorm:"column:is_active;type:boolean" json:"is_active"`
	IsDeleted        *bool      `gorm:"column:is_deleted;type:boolean" json:"is_deleted"`
}

// TableName ProvisionHostingDelete's table name
func (*ProvisionHostingDelete) TableName() string {
	return TableNameProvisionHostingDelete
}
