// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvisionHostingCertificateCreate = "provision_hosting_certificate_create"

// ProvisionHostingCertificateCreate mapped from table <provision_hosting_certificate_create>
type ProvisionHostingCertificateCreate struct {
	CreatedDate      *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate      *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy        *string    `gorm:"column:created_by;type:text;default:CURRENT_USER" json:"created_by"`
	UpdatedBy        *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID               string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TenantCustomerID string     `gorm:"column:tenant_customer_id;type:uuid;not null" json:"tenant_customer_id"`
	ProvisionedDate  *time.Time `gorm:"column:provisioned_date;type:timestamp with time zone" json:"provisioned_date"`
	StatusID         string     `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('provision_status'::text, 'pending'::text)" json:"status_id"`
	Roid             *string    `gorm:"column:roid;type:text" json:"roid"`
	JobID            *string    `gorm:"column:job_id;type:uuid" json:"job_id"`
	OrderItemPlanIds *string    `gorm:"column:order_item_plan_ids;type:uuid[]" json:"order_item_plan_ids"`
	OrderMetadata    *string    `gorm:"column:order_metadata;type:jsonb;default:{}" json:"order_metadata"`
	ResultMessage    *string    `gorm:"column:result_message;type:text" json:"result_message"`
	ResultData       *string    `gorm:"column:result_data;type:jsonb" json:"result_data"`
	HostingID        string     `gorm:"column:hosting_id;type:uuid;not null" json:"hosting_id"`
	CertificateID    *string    `gorm:"column:certificate_id;type:uuid" json:"certificate_id"`
	DomainName       string     `gorm:"column:domain_name;type:text;not null" json:"domain_name"`
	Body             *string    `gorm:"column:body;type:text" json:"body"`
	Chain            *string    `gorm:"column:chain;type:text" json:"chain"`
	PrivateKey       *string    `gorm:"column:private_key;type:text" json:"private_key"`
	NotBefore        *time.Time `gorm:"column:not_before;type:timestamp with time zone" json:"not_before"`
	NotAfter         *time.Time `gorm:"column:not_after;type:timestamp with time zone" json:"not_after"`
}

// TableName ProvisionHostingCertificateCreate's table name
func (*ProvisionHostingCertificateCreate) TableName() string {
	return TableNameProvisionHostingCertificateCreate
}
