// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvisionHostingCreate = "provision_hosting_create"

// ProvisionHostingCreate mapped from table <provision_hosting_create>
type ProvisionHostingCreate struct {
	CreatedDate      *time.Time `gorm:"column:created_date;type:timestamp with time zone;default:now()" json:"created_date"`
	UpdatedDate      *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy        *string    `gorm:"column:created_by;type:text" json:"created_by"`
	UpdatedBy        *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID               string     `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TenantCustomerID string     `gorm:"column:tenant_customer_id;type:uuid;not null" json:"tenant_customer_id"`
	ProvisionedDate  *time.Time `gorm:"column:provisioned_date;type:timestamp with time zone" json:"provisioned_date"`
	StatusID         string     `gorm:"column:status_id;type:uuid;not null;default:tc_id_from_name('provision_status'::text, 'pending'::text)" json:"status_id"`
	Roid             *string    `gorm:"column:roid;type:text" json:"roid"`
	JobID            *string    `gorm:"column:job_id;type:uuid" json:"job_id"`
	OrderItemPlanIds *string    `gorm:"column:order_item_plan_ids;type:uuid[]" json:"order_item_plan_ids"`
	OrderMetadata    *string    `gorm:"column:order_metadata;type:jsonb;default:{}" json:"order_metadata"`
	ResultMessage    *string    `gorm:"column:result_message;type:text" json:"result_message"`
	ResultData       *string    `gorm:"column:result_data;type:jsonb" json:"result_data"`
	HostingID        string     `gorm:"column:hosting_id;type:uuid;not null" json:"hosting_id"`
	DomainName       string     `gorm:"column:domain_name;type:text;not null" json:"domain_name"`
	RegionID         string     `gorm:"column:region_id;type:uuid;not null" json:"region_id"`
	ClientID         string     `gorm:"column:client_id;type:uuid;not null" json:"client_id"`
	ClientUsername   *string    `gorm:"column:client_username;type:text" json:"client_username"`
	ProductID        string     `gorm:"column:product_id;type:uuid;not null" json:"product_id"`
	CertificateID    *string    `gorm:"column:certificate_id;type:uuid" json:"certificate_id"`
	ExternalOrderID  *string    `gorm:"column:external_order_id;type:text" json:"external_order_id"` // unique order id generated by the external hosting backend
	ExternalClientID *string    `gorm:"column:external_client_id;type:text" json:"external_client_id"`
	HostingStatusID  *string    `gorm:"column:hosting_status_id;type:uuid" json:"hosting_status_id"`
	IsActive         bool       `gorm:"column:is_active;type:boolean;not null" json:"is_active"`
	IsDeleted        bool       `gorm:"column:is_deleted;type:boolean;not null" json:"is_deleted"`
}

// TableName ProvisionHostingCreate's table name
func (*ProvisionHostingCreate) TableName() string {
	return TableNameProvisionHostingCreate
}
