// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRgpStatus = "rgp_status"

// RgpStatus mapped from table <rgp_status>
type RgpStatus struct {
	ID      string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name    string `gorm:"column:name;type:text;not null" json:"name"`
	EppName string `gorm:"column:epp_name;type:text;not null" json:"epp_name"`
	Descr   string `gorm:"column:descr;type:text;not null" json:"descr"`
}

// TableName RgpStatus's table name
func (*RgpStatus) TableName() string {
	return TableNameRgpStatus
}
