// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTransferStatus = "transfer_status"

// TransferStatus mapped from table <transfer_status>
type TransferStatus struct {
	ID        string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name      string `gorm:"column:name;type:text;not null" json:"name"`
	Descr     string `gorm:"column:descr;type:text;not null" json:"descr"`
	IsFinal   bool   `gorm:"column:is_final;type:boolean;not null" json:"is_final"`
	IsSuccess bool   `gorm:"column:is_success;type:boolean;not null" json:"is_success"`
}

// TableName TransferStatus's table name
func (*TransferStatus) TableName() string {
	return TableNameTransferStatus
}
