// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTransferInDomainSecdnsDsDatum = "transfer_in_domain_secdns_ds_data"

// TransferInDomainSecdnsDsDatum mapped from table <transfer_in_domain_secdns_ds_data>
type TransferInDomainSecdnsDsDatum struct {
	ID                          string  `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	KeyTag                      uint32  `gorm:"column:key_tag;type:integer;not null" json:"key_tag"`
	Algorithm                   uint32  `gorm:"column:algorithm;type:integer;not null" json:"algorithm"`
	DigestType                  uint32  `gorm:"column:digest_type;type:integer;not null;default:1" json:"digest_type"`
	Digest                      string  `gorm:"column:digest;type:text;not null" json:"digest"`
	KeyDataID                   *string `gorm:"column:key_data_id;type:uuid" json:"key_data_id"`
	ProvisionDomainTransferInID string  `gorm:"column:provision_domain_transfer_in_id;type:uuid;not null" json:"provision_domain_transfer_in_id"`
}

// TableName TransferInDomainSecdnsDsDatum's table name
func (*TransferInDomainSecdnsDsDatum) TableName() string {
	return TableNameTransferInDomainSecdnsDsDatum
}
