// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTransferInDomainSecdnsKeyDatum = "transfer_in_domain_secdns_key_data"

// TransferInDomainSecdnsKeyDatum mapped from table <transfer_in_domain_secdns_key_data>
type TransferInDomainSecdnsKeyDatum struct {
	ID                          string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Flags                       uint32 `gorm:"column:flags;type:integer;not null" json:"flags"`
	Protocol                    uint32 `gorm:"column:protocol;type:integer;not null;default:3" json:"protocol"`
	Algorithm                   uint32 `gorm:"column:algorithm;type:integer;not null" json:"algorithm"`
	PublicKey                   string `gorm:"column:public_key;type:text;not null" json:"public_key"`
	ProvisionDomainTransferInID string `gorm:"column:provision_domain_transfer_in_id;type:uuid;not null" json:"provision_domain_transfer_in_id"`
}

// TableName TransferInDomainSecdnsKeyDatum's table name
func (*TransferInDomainSecdnsKeyDatum) TableName() string {
	return TableNameTransferInDomainSecdnsKeyDatum
}
