// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVAccreditationTld = "v_accreditation_tld"

// VAccreditationTld mapped from table <v_accreditation_tld>
type VAccreditationTld struct {
	TenantID             *string `gorm:"column:tenant_id;type:uuid" json:"tenant_id"`
	TenantName           *string `gorm:"column:tenant_name;type:text" json:"tenant_name"`
	AccreditationID      *string `gorm:"column:accreditation_id;type:uuid" json:"accreditation_id"`
	AccreditationName    *string `gorm:"column:accreditation_name;type:text" json:"accreditation_name"`
	AccreditationTldID   *string `gorm:"column:accreditation_tld_id;type:uuid" json:"accreditation_tld_id"`
	TenantCustomerID     *string `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	TenantCustomerNumber *string `gorm:"column:tenant_customer_number;type:text" json:"tenant_customer_number"`
	CustomerID           *string `gorm:"column:customer_id;type:uuid" json:"customer_id"`
	CustomerName         *string `gorm:"column:customer_name;type:text" json:"customer_name"`
	TldID                *string `gorm:"column:tld_id;type:uuid" json:"tld_id"`
	TldName              *string `gorm:"column:tld_name;type:text" json:"tld_name"`
	ProviderName         *string `gorm:"column:provider_name;type:text" json:"provider_name"`
	ProviderID           *string `gorm:"column:provider_id;type:uuid" json:"provider_id"`
	ProviderInstanceID   *string `gorm:"column:provider_instance_id;type:uuid" json:"provider_instance_id"`
	ProviderInstanceName *string `gorm:"column:provider_instance_name;type:text" json:"provider_instance_name"`
	IsProxy              *bool   `gorm:"column:is_proxy;type:boolean" json:"is_proxy"`
	IsDefault            *bool   `gorm:"column:is_default;type:boolean" json:"is_default"`
}

// TableName VAccreditationTld's table name
func (*VAccreditationTld) TableName() string {
	return TableNameVAccreditationTld
}
