// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVAttribute = "v_attribute"

// VAttribute mapped from table <v_attribute>
type VAttribute struct {
	TenantID           *string `gorm:"column:tenant_id;type:uuid" json:"tenant_id"`
	TenantName         *string `gorm:"column:tenant_name;type:text" json:"tenant_name"`
	TldName            *string `gorm:"column:tld_name;type:text" json:"tld_name"`
	TldID              *string `gorm:"column:tld_id;type:uuid" json:"tld_id"`
	Path               *string `gorm:"column:path;type:text" json:"path"`
	CategoryID         *string `gorm:"column:category_id;type:uuid" json:"category_id"`
	KeyID              *string `gorm:"column:key_id;type:uuid" json:"key_id"`
	DataType           *string `gorm:"column:data_type;type:regtype" json:"data_type"`
	DataTypeName       *string `gorm:"column:data_type_name;type:text" json:"data_type_name"`
	Key                *string `gorm:"column:key;type:text" json:"key"`
	Value              string  `gorm:"column:value;type:text" json:"value"`
	IsDefault          *bool   `gorm:"column:is_default;type:boolean" json:"is_default"`
	AccreditationTldID string  `gorm:"column:accreditation_tld_id;type:uuid" json:"accreditation_tld_id"`
}

// TableName VAttribute's table name
func (*VAttribute) TableName() string {
	return TableNameVAttribute
}
