// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVDomain = "v_domain"

// VDomain mapped from table <v_domain>
type VDomain struct {
	CreatedDate        *time.Time `gorm:"column:created_date;type:timestamp with time zone" json:"created_date"`
	UpdatedDate        *time.Time `gorm:"column:updated_date;type:timestamp with time zone" json:"updated_date"`
	CreatedBy          *string    `gorm:"column:created_by;type:text" json:"created_by"`
	UpdatedBy          *string    `gorm:"column:updated_by;type:text" json:"updated_by"`
	ID                 *string    `gorm:"column:id;type:uuid" json:"id"`
	TenantCustomerID   *string    `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	AccreditationTldID *string    `gorm:"column:accreditation_tld_id;type:uuid" json:"accreditation_tld_id"`
	Name               *string    `gorm:"column:name;type:text" json:"name"`
	AuthInfo           *string    `gorm:"column:auth_info;type:text" json:"auth_info"`
	Roid               *string    `gorm:"column:roid;type:text" json:"roid"`
	RyCreatedDate      *time.Time `gorm:"column:ry_created_date;type:timestamp with time zone" json:"ry_created_date"`
	RyExpiryDate       *time.Time `gorm:"column:ry_expiry_date;type:timestamp with time zone" json:"ry_expiry_date"`
	RyUpdatedDate      *time.Time `gorm:"column:ry_updated_date;type:timestamp with time zone" json:"ry_updated_date"`
	RyTransferedDate   *time.Time `gorm:"column:ry_transfered_date;type:timestamp with time zone" json:"ry_transfered_date"`
	DeletedDate        *time.Time `gorm:"column:deleted_date;type:timestamp with time zone" json:"deleted_date"`
	ExpiryDate         *time.Time `gorm:"column:expiry_date;type:timestamp with time zone" json:"expiry_date"`
	AutoRenew          *bool      `gorm:"column:auto_renew;type:boolean" json:"auto_renew"`
	Metadata           *string    `gorm:"column:metadata;type:jsonb" json:"metadata"`
	RgpStatusID        *string    `gorm:"column:rgp_status_id;type:uuid" json:"rgp_status_id"`
	RgpEppStatus       *string    `gorm:"column:rgp_epp_status;type:text" json:"rgp_epp_status"`
}

// TableName VDomain's table name
func (*VDomain) TableName() string {
	return TableNameVDomain
}
