// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/jmoiron/sqlx/types"
	"time"
)

const TableNameVJob = "v_job"

// VJob mapped from table <v_job>
type VJob struct {
	JobID            *string        `gorm:"column:job_id;type:uuid" json:"job_id"`
	JobParentID      *string        `gorm:"column:job_parent_id;type:uuid" json:"job_parent_id"`
	TenantCustomerID *string        `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	JobStatusName    *string        `gorm:"column:job_status_name;type:text" json:"job_status_name"`
	JobTypeName      *string        `gorm:"column:job_type_name;type:text" json:"job_type_name"`
	CreatedDate      *time.Time     `gorm:"column:created_date;type:timestamp with time zone" json:"created_date"`
	StartDate        *time.Time     `gorm:"column:start_date;type:timestamp with time zone" json:"start_date"`
	EndDate          *time.Time     `gorm:"column:end_date;type:timestamp with time zone" json:"end_date"`
	RetryDate        *time.Time     `gorm:"column:retry_date;type:timestamp with time zone" json:"retry_date"`
	RetryCount       *int32         `gorm:"column:retry_count;type:integer" json:"retry_count"`
	ReferenceID      *string        `gorm:"column:reference_id;type:uuid" json:"reference_id"`
	ReferenceTable   *string        `gorm:"column:reference_table;type:text" json:"reference_table"`
	ResultMsg        *string        `gorm:"column:result_msg;type:text" json:"result_msg"`
	ResultData       types.JSONText `gorm:"column:result_data;type:jsonb" json:"result_data"`
	Data             types.JSONText `gorm:"column:data;type:jsonb" json:"data"`
	TenantCustomer   types.JSONText `gorm:"column:tenant_customer;type:jsonb" json:"tenant_customer"`
	RoutingKey       *string        `gorm:"column:routing_key;type:text" json:"routing_key"`
	JobStatusIsFinal *bool          `gorm:"column:job_status_is_final;type:boolean" json:"job_status_is_final"`
	EventID          *string        `gorm:"column:event_id;type:text" json:"event_id"`
}

// TableName VJob's table name
func (*VJob) TableName() string {
	return TableNameVJob
}
