// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVOrderTransferAwayDomain = "v_order_transfer_away_domain"

// VOrderTransferAwayDomain mapped from table <v_order_transfer_away_domain>
type VOrderTransferAwayDomain struct {
	OrderItemID          string     `gorm:"column:order_item_id;type:uuid" json:"order_item_id"`
	OrderID              string     `gorm:"column:order_id;type:uuid" json:"order_id"`
	AccreditationTldID   string     `gorm:"column:accreditation_tld_id;type:uuid" json:"accreditation_tld_id"`
	OrderMetadata        *string    `gorm:"column:order_metadata;type:jsonb" json:"order_metadata"`
	TenantCustomerID     *string    `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	TypeID               *string    `gorm:"column:type_id;type:uuid" json:"type_id"`
	CustomerUserID       *string    `gorm:"column:customer_user_id;type:uuid" json:"customer_user_id"`
	StatusID             *string    `gorm:"column:status_id;type:uuid" json:"status_id"`
	StatusName           string     `gorm:"column:status_name;type:text" json:"status_name"`
	StatusDescr          *string    `gorm:"column:status_descr;type:text" json:"status_descr"`
	StatusIsFinal        *bool      `gorm:"column:status_is_final;type:boolean" json:"status_is_final"`
	TenantID             *string    `gorm:"column:tenant_id;type:uuid" json:"tenant_id"`
	CustomerID           *string    `gorm:"column:customer_id;type:uuid" json:"customer_id"`
	TenantName           *string    `gorm:"column:tenant_name;type:text" json:"tenant_name"`
	Name                 *string    `gorm:"column:name;type:text" json:"name"`
	ProviderName         *string    `gorm:"column:provider_name;type:text" json:"provider_name"`
	ProviderInstanceID   *string    `gorm:"column:provider_instance_id;type:uuid" json:"provider_instance_id"`
	ProviderInstanceName *string    `gorm:"column:provider_instance_name;type:text" json:"provider_instance_name"`
	TldID                *string    `gorm:"column:tld_id;type:uuid" json:"tld_id"`
	TldName              *string    `gorm:"column:tld_name;type:text" json:"tld_name"`
	AccreditationID      string     `gorm:"column:accreditation_id;type:uuid" json:"accreditation_id"`
	DomainName           string     `gorm:"column:domain_name;type:fqdn" json:"domain_name"`
	TransferStatusID     *string    `gorm:"column:transfer_status_id;type:uuid" json:"transfer_status_id"`
	TransferStatus       string     `gorm:"column:transfer_status_name;type:text" json:"transfer_status_name"`
	RequestedBy          *string    `gorm:"column:requested_by;type:text" json:"requested_by"`
	RequestedDate        *time.Time `gorm:"column:requested_date;type:timestamp with time zone" json:"requested_date"`
	ActionBy             *string    `gorm:"column:action_by;type:text" json:"action_by"`
	ActionDate           *time.Time `gorm:"column:action_date;type:timestamp with time zone" json:"action_date"`
	ExpiryDate           *time.Time `gorm:"column:expiry_date;type:timestamp with time zone" json:"expiry_date"`
	AuthInfo             *string    `gorm:"column:auth_info;type:text" json:"auth_info"`
	Metadata             *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
}

// TableName VOrderTransferAwayDomain's table name
func (*VOrderTransferAwayDomain) TableName() string {
	return TableNameVOrderTransferAwayDomain
}
