// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVOrderType = "v_order_type"

// VOrderType mapped from table <v_order_type>
type VOrderType struct {
	ProductID   *string `gorm:"column:product_id;type:uuid" json:"product_id"`
	ProductName *string `gorm:"column:product_name;type:text" json:"product_name"`
	ID          *string `gorm:"column:id;type:uuid" json:"id"`
	Name        *string `gorm:"column:name;type:text" json:"name"`
}

// TableName VOrderType's table name
func (*VOrderType) TableName() string {
	return TableNameVOrderType
}
