// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVProvisionDomain = "v_provision_domain"

// VProvisionDomain mapped from table <v_provision_domain>
type VProvisionDomain struct {
	ID                *string `gorm:"column:id;type:uuid" json:"id"`
	AccreditationID   *string `gorm:"column:accreditation_id;type:uuid" json:"accreditation_id"`
	AccreditationName *string `gorm:"column:accreditation_name;type:text" json:"accreditation_name"`
	TenantCustomerID  *string `gorm:"column:tenant_customer_id;type:uuid" json:"tenant_customer_id"`
	DomainName        *string `gorm:"column:domain_name;type:fqdn" json:"domain_name"`
	RyCltrid          *string `gorm:"column:ry_cltrid;type:text" json:"ry_cltrid"`
	StatusID          *string `gorm:"column:status_id;type:uuid" json:"status_id"`
	ReferenceTable    *string `gorm:"column:reference_table;type:text" json:"reference_table"`
}

// TableName VProvisionDomain's table name
func (*VProvisionDomain) TableName() string {
	return TableNameVProvisionDomain
}
