# These values are used for local run
# For DEV they will be overwritten during deployment

log:
  outputsink: stderr

rmq:
  hostname: rabbitmq-local
  port: 5671
  username: domains
  password: tucows
  exchange: test
  exchangekind: direct
  queuetype: classic
  tlsenabled: true
  tlsskipverify: true
  finalstatusqueue:
    name: final_status_notification
  emailrenderingqueue:
    name: template_rendering_response
  emailnotificationqueue:
    name: email_notification
  verifyservername:

# Database configuration
subscriptiondb:
  hostname: subdb
  port: 5432
  username: tucows
  password: tucows1234
  dbname: subtdpdb
